In [2]:
import numpy as np

In [3]:
I_2 = np.array([
    [1, 0],
    [0, 1]
])
Z = np.array([
    [1, 0],
    [0, -1]
])
X = np.array([
    [0, 1],
    [1, 0]
])

In [4]:
def is_unitary(M):
    return np.allclose(np.eye(len(M)), M.dot(M.T.conj()))

In [5]:
np.kron(I_2, I_2)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
A_I = np.kron(I_2, np.kron(I_2, I_2))
A_R = np.kron(Z, np.kron(X, X))

A = 1/2 * (A_I - A_R)
print(A_I)
print(A_R)
print(A)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
[[ 0  0  0  1  0  0  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  0 -1  0  0  0]]
[[ 0.5  0.   0.  -0.5  0.   0.   0.   0. ]
 [ 0.   0.5 -0.5  0.   0.   0.   0.   0. ]
 [ 0.  -0.5  0.5  0.   0.   0.   0.   0. ]
 [-0.5  0.   0.   0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.5  0.   0.   0.5]
 [ 0.   0.   0.   0.   0.   0.5  0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.5  0.5  0. ]
 [ 0.   0.   0.   0.   0.5  0.   0.   0.5]]


In [7]:
print(A - A.T)
print(A @ A.T)
print(A @ A.T - A)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 0.5  0.   0.  -0.5  0.   0.   0.   0. ]
 [ 0.   0.5 -0.5  0.   0.   0.   0.   0. ]
 [ 0.  -0.5  0.5  0.   0.   0.   0.   0. ]
 [-0.5  0.   0.   0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.5  0.   0.   0.5]
 [ 0.   0.   0.   0.   0.   0.5  0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.5  0.5  0. ]
 [ 0.   0.   0.   0.   0.5  0.   0.   0.5]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
print(is_unitary(A), is_unitary(A_I), is_unitary(A_R))

False True True
